//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LVT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LVT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{{ v:&apos;{0}&apos;, f:&apos;{1}&lt;div style=\&quot;font-style:italic\&quot;&gt;{2}&lt;/div&gt;&lt;div style =\&quot;font-style:italic\&quot;&gt;{3}&lt;/div&gt;&apos;}}, &apos;{4}&apos;].
        /// </summary>
        internal static string OrgChartEpicString {
            get {
                return ResourceManager.GetString("OrgChartEpicString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{{ v:&apos;{0}&apos;, f:&apos;{1}&lt;div style=\&quot;font-style:italic\&quot;&gt;{2}&lt;/div&gt;&lt;div style=\&quot;font-style:italic\&quot;&gt;{3}&lt;/div&gt;&lt;div style=\&quot;font-style:italic\&quot;&gt;{4}&lt;/div&gt;&lt;div style=\&quot;font-style:italic\&quot;&gt;{5}&lt;/div&gt;&apos;}}, &apos;{6}&apos;].
        /// </summary>
        internal static string OrgChartMeasureString {
            get {
                return ResourceManager.GetString("OrgChartMeasureString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{{ v:&apos;{0}&apos;, f:&apos;{1}&lt;div style=\&quot;font-style:italic\&quot;&gt;{2}&lt;/div&gt;&apos;}}, &apos;{3}&apos;].
        /// </summary>
        internal static string OrgChartNodeString {
            get {
                return ResourceManager.GetString("OrgChartNodeString", resourceCulture);
            }
        }
    }
}
